### PR TITLE
Add CI pipeline and some upstream changes

### PR DESCRIPTION
**Pull request by muhammad-st**
## Overview

APR to build the gem with the native extension to avoid issues with building as part of bundle install

Currently, I'm building the package in Github actions and publishing them in Jenkins.

## Stakeholders 
- @andreyzhelnin-st 
- @IvanTakarlikov-st 
- @kacperkaminski-st 
- @ST-eugenekrivdyuk

### CODE REVIEW

**Review by IvanTakarlikov-st — APPROVED** [review]
Looks good to me, but please make sure to spawn custom branch using this new version of gem, and make sure it passing. 
But changes doesn't seems to be changing hashing calculation mechanism to me. 
Probably it's good idea to verify with related teams some test cases.

**Comment by muhammad-st** [comment]
Checked usage on overseer using:
```ruby
update = ScreenshotUpdate::Itunes.find_by(
  :app_id => 324684580,
  :country => "US",
  :date => Date.new(2023, 11, 29)
)

update.before_phone_screenshots.zip(update.after_phone_screenshots).map do |before, after|
  distance = Util.open_and_phashion(before).distance_from(Util.open_and_phashion(after))
  [before, after, distance]
end
```


Output of this branch (included as a gem)

```
[["https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/6f/e1/23/6fe12367-42bb-b3fb-46a6-a98afa214c3a/bf9a1515-e5ce-4cae-bec1-2b53dc69f4ce_IOS_-_6.7_-_S01_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource126/v4/08/83/de/0883de6b-4615-4a41-0013-eaac0b258345/0265ec5e-b9ac-4c2f-9d95-2de3f284b0ec_IOS_-_6.7_-_S01_-_EN-US.png/1290x2796bb.png",
  20],
 ["https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/fb/00/e1/fb00e11a-0fdb-674b-f7f2-6af439861997/1e39c100-2a2d-43b5-b0dd-8c540de1ae3e_IOS_-_6.7_-_S02_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource126/v4/ec/b4/2b/ecb42b34-b289-095c-1891-0ed03bb57cc4/e6c4993b-f6e2-4b07-873d-afcb011acb30_IOS_-_6.7_-_S02_-_EN-US.png/1290x2796bb.png",
  12],
 ["https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/e7/85/68/e78568a5-5014-fd06-6f8a-a2b9133627df/a079bf38-4647-4fdd-a652-6ff55d66d2f7_IOS_-_6.7_-_S03_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/e2/b6/f4/e2b6f400-4342-02d6-1d11-2a8fc7c123d7/5953db43-4430-425a-9228-911aa8e783b9_IOS_-_6.7_-_S03_-_EN-US.png/1290x2796bb.png",
  22],
 ["https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/a8/71/13/a87113b9-3790-e603-a8e1-5ee4a6b4334e/fc7db0b7-83e3-4cc4-9641-712a5c8777ba_IOS_-_6.7_-_S04_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/27/bf/37/27bf3762-d85e-e603-ab60-883bb6508eaa/1c9b59de-280b-4a8b-b571-47fd96546e62_IOS_-_6.7_-_S04_-_EN-US.png/1290x2796bb.png",
  8],
 ["https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/7e/89/30/7e89306f-57a6-ed06-b998-fa7cb02162cc/c94378ed-9da3-407d-ae53-131967ce2a9a_IOS_-_6.7_-_S05_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/86/66/2b/86662b92-971d-29cd-5798-ab4a6417e42f/94000d25-d85e-44bb-a53f-11961af44f98_IOS_-_6.7_-_S05_-_EN-US.png/1290x2796bb.png",
  4],
 ["https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/ef/2f/6e/ef2f6e80-0260-accf-b6b5-ad123129c860/98150008-b83d-4b22-a2dc-b3fc43854daf_IOS_-_6.7_-_S06_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource126/v4/20/de/18/20de18f3-3356-29e5-76b3-db636e21189f/1e363551-c855-4a85-b067-d99874b44202_IOS_-_6.7_-_S06_-_EN-US.png/1290x2796bb.png",
  0],
 ["https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/a0/b9/2f/a0b92fea-d356-0ab1-8a92-dac68b5459d7/95893f97-4faf-49bb-ac93-7770a9ac0944_IOS_-_6.7_-_S07_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/43/09/18/430918ab-9dbb-67e6-1408-1145cd567198/9204ca59-c4e2-4b01-958e-da4ffac4627a_IOS_-_6.7_-_S07_-_EN-US.png/1290x2796bb.png",
  0],
 ["https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/a5/06/ce/a506ce6d-67bd-bef0-d180-a4b464e854b9/109734c7-e25e-45a1-99f6-7de52aef4bf9_IOS_-_6.7_-_S08_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/a2/97/26/a29726b9-ddfb-7bcc-4ca8-1eb4844012c7/aa1ee658-f910-44c2-95d6-c5f71fa27494_IOS_-_6.7_-_S08_-_EN-US.png/1290x2796bb.png",
  0]]
```

Compared to master branch

```
[["https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/6f/e1/23/6fe12367-42bb-b3fb-46a6-a98afa214c3a/bf9a1515-e5ce-4cae-bec1-2b53dc69f4ce_IOS_-_6.7_-_S01_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource126/v4/08/83/de/0883de6b-4615-4a41-0013-eaac0b258345/0265ec5e-b9ac-4c2f-9d95-2de3f284b0ec_IOS_-_6.7_-_S01_-_EN-US.png/1290x2796bb.png",
  20],
 ["https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/fb/00/e1/fb00e11a-0fdb-674b-f7f2-6af439861997/1e39c100-2a2d-43b5-b0dd-8c540de1ae3e_IOS_-_6.7_-_S02_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource126/v4/ec/b4/2b/ecb42b34-b289-095c-1891-0ed03bb57cc4/e6c4993b-f6e2-4b07-873d-afcb011acb30_IOS_-_6.7_-_S02_-_EN-US.png/1290x2796bb.png",
  12],
 ["https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/e7/85/68/e78568a5-5014-fd06-6f8a-a2b9133627df/a079bf38-4647-4fdd-a652-6ff55d66d2f7_IOS_-_6.7_-_S03_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/e2/b6/f4/e2b6f400-4342-02d6-1d11-2a8fc7c123d7/5953db43-4430-425a-9228-911aa8e783b9_IOS_-_6.7_-_S03_-_EN-US.png/1290x2796bb.png",
  22],
 ["https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/a8/71/13/a87113b9-3790-e603-a8e1-5ee4a6b4334e/fc7db0b7-83e3-4cc4-9641-712a5c8777ba_IOS_-_6.7_-_S04_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/27/bf/37/27bf3762-d85e-e603-ab60-883bb6508eaa/1c9b59de-280b-4a8b-b571-47fd96546e62_IOS_-_6.7_-_S04_-_EN-US.png/1290x2796bb.png",
  8],
 ["https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/7e/89/30/7e89306f-57a6-ed06-b998-fa7cb02162cc/c94378ed-9da3-407d-ae53-131967ce2a9a_IOS_-_6.7_-_S05_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/86/66/2b/86662b92-971d-29cd-5798-ab4a6417e42f/94000d25-d85e-44bb-a53f-11961af44f98_IOS_-_6.7_-_S05_-_EN-US.png/1290x2796bb.png",
  4],
 ["https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/ef/2f/6e/ef2f6e80-0260-accf-b6b5-ad123129c860/98150008-b83d-4b22-a2dc-b3fc43854daf_IOS_-_6.7_-_S06_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource126/v4/20/de/18/20de18f3-3356-29e5-76b3-db636e21189f/1e363551-c855-4a85-b067-d99874b44202_IOS_-_6.7_-_S06_-_EN-US.png/1290x2796bb.png",
  0],
 ["https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/a0/b9/2f/a0b92fea-d356-0ab1-8a92-dac68b5459d7/95893f97-4faf-49bb-ac93-7770a9ac0944_IOS_-_6.7_-_S07_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/43/09/18/430918ab-9dbb-67e6-1408-1145cd567198/9204ca59-c4e2-4b01-958e-da4ffac4627a_IOS_-_6.7_-_S07_-_EN-US.png/1290x2796bb.png",
  0],
 ["https://is1-ssl.mzstatic.com/image/thumb/Purple116/v4/a5/06/ce/a506ce6d-67bd-bef0-d180-a4b464e854b9/109734c7-e25e-45a1-99f6-7de52aef4bf9_IOS_-_6.7_-_S08_-_EN-US.png/1290x2796bb.png",
  "https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/a2/97/26/a29726b9-ddfb-7bcc-4ca8-1eb4844012c7/aa1ee658-f910-44c2-95d6-c5f71fa27494_IOS_-_6.7_-_S08_-_EN-US.png/1290x2796bb.png",
  0]]
```

Output is identical.

**Comment by muhammad-st** [comment]
Additionally, CI is passing properly on [overseer's branch](https://github.com/sensortower/overseer/pull/37294) that uses this branch of the gem (included as a gem).

**Comment by stasmakutin-st** [comment]
@muhammad-st were there any differences in fingerprints between master branch and yours?

**Comment by muhammad-st** [comment]
> @muhammad-st were there any differences in fingerprints between master branch and yours?

I was not able to compare the complete list (line length was in Kilo bytes). for the compared amount (can be seen in the modified snippet above) the results were matching (using `diff / git diff`).

**Review by stasmakutin-st — APPROVED** [review]

**Pull request merged**
